name: cities_of_the_world
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^4.0.0-dev.2
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  skeletonizer: ^1.4.2
  dio: ^5.7.0
  injectable: ^2.5.0
  get_it: ^8.0.2
  path_provider: ^2.1.5
  isar_flutter_libs: ^4.0.0-dev.14
  world_countries: ^2.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
